@eAppointmentServer.WebAPI_HostAddress = http://localhost:5053

post http://localhost:5053/api/auth/login
Accept: application/json
Content-Type: application/json
{
  "userNameOrEmail":"admin",
  "password":"1"
}

###
